version: '3'

services:

  php-fpm:
    container_name: joliquiz-php
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@host.docker.internal:3306/${DATABASE_NAME}      
      # - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
      # - DATABASE_URL=pgsql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?charset=UTF-8
      # - DATABASE_URL=sqlite:///%kernel.project_dir%/var/${DATABASE_NAME}.db
      - MAILER_URL=${MAILER_URL}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - LOCALE=${LOCALE}
    volumes:
      - ./joliquiz/src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000

  nginx:
    container_name: joliquiz-web
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./joliquiz/src:/var/www
      - ./joliquiz/var/log/nginx:/var/log/nginx
    depends_on:
      - php-fpm
    ports:
      - "8080:80"

